# 나의 첫 신경망 학습

저번 시간 우리는 토치에서 신경망을 정의하는 방법에 대하여 알아보았다. 오늘은 정의한 신경망을 어떻게 학습하는가에 대하여 알아보도록 하자. 

## 학습 준비 - 데이터 만들기

필자는 유튜브에 R을 사용한 통계관련 수업들을 올려놓았다. 그 수업에서 큰 축을 이루는 것이 바로 회귀분석이다. 회귀분석은 주어진 데이터를 모델링할 때 신경망의 가장 큰 장점은 회귀직선과 같은 선형모형들이 가지는 한계를 넘어서, 비선형 모델링을 할 수 있게 해준다는 것이다. 이러한 장점들을 잘 확인해보기 위해서 비선형 모델에서 관찰값을 뽑아 모의 데이터로 만들어 보도록 하자.

```{r, message=FALSE, warning=FALSE}
library(tidyverse)

# x 자리 임의 생성
x <- sort(sample(1:100, 40))

# 모델을 위한 f 함수 정의
f <- function(x){
    x + 20 * sin(0.2 * x)
}

# noise을 가미한 관찰값 생성
y <- f(x) + 10 * rnorm(40)

obs_data <- tibble(x = x, y = y)
head(obs_data)
```

데이터를 그려보도록 하자.

```{r data-vis, echo=TRUE, fig.cap="샘플 데이터 시각화. 비선형성이 잘 드러나있다.", fig.align='center', out.width = '100%'}
library(ggthemes)
library(latex2exp)

theme_set(theme_igray())

x_true <- 1:100

model_data <- tibble(x = x_true, y = f(x_true))

obs_data %>% 
    ggplot(aes(x = x, y = y)) +
    geom_point() +
    geom_line(data = model_data, aes(x = x, y = y), linetype = "dashed") +
    labs(x = "x", y = "f(x)")
```



